### ISSUE TITLE
数据来源

### ISSUE THREAD

**Issue by GZYZG** [jiangnanboy/education_knowledge_graph_app#2]
您好，请问构建的知识图谱的数据来自哪里，能否分享一下😆

**Comment by jiangnanboy** [comment]
数据是公司的，没法分享，不好意思





------------------ 原始邮件 ------------------
发件人: GuoZhiyan ***@***.***&gt;
发送时间: 2021年9月13日 22:06
收件人: jiangnanboy/education_knowledge_graph_app ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[jiangnanboy/education_knowledge_graph_app] 数据来源 (#2)





 
您好，请问构建的知识图谱的数据来自哪里，能否分享一下😆
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
